version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    environment:
      - PORT=3000
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - DEBUG_ASSETS=false
      - RACK_TIMEOUT=5000
    restart: on-failure
    command:
      ./bin/run_server.sh
  db:
    image: mysql:5.6
    ports:
      - "3320:3306"
    environment:
      - MYSQL_DATABASE=potato
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./.docker/mysql:/var/lib/mysql
